### ISSUE TITLE
Typo: Shaply value instead of Shapley Value

### ISSUE THREAD

**Issue by lepennec** [amueller/COMS4995-s20#9]
Thank you for this tremendeous set of slides!

I've spotted a typo in aml11 "Model Interpretation and Feature Selection"  Slides 11: Shaply value should be Shapley value. 

I've also seen that the name of the script still refers to aml12.

**Comment by amueller** [comment]
thanks! yeah, the notebooks are not numbered correctly. Do you want to send a PR for the typo?

Cheers!

**Comment by lepennec** [comment]
OK. I was assuming that the source were missing but I see now that the html
is the source ;-)

**Comment by amueller** [comment]
Yes indeed! All there for the taking ;) Thanks for the fix.
